package com.mikrotikmanager.support;

public enum ApiErrorCode {
    MIKROTIK_UNAVAILABLE,
    MIKROTIK_AUTHENTICATION_FAILED,
    DEVICE_NOT_FOUND,
    PORT_NOT_FOUND,
    INVALID_SPEED_LIMIT,
    INVALID_INPUT,
    MIKROTIK_WRITES_DISABLED,
    MIKROTIK_OPERATION_FAILED,
    RESOURCE_NOT_MANAGED,
    INTERNAL_ERROR
}
