package com.mikrotikmanager.support;

public enum ApiErrorCode {
    MIKROTIK_UNAVAILABLE,
    MIKROTIK_AUTHENTICATION_FAILED,
    MIKROTIK_BAD_RESPONSE,
    MIKROTIK_TLS_ERROR,
    DEVICE_NOT_FOUND,
    PORT_NOT_FOUND,
    INVALID_SPEED_LIMIT,
    INVALID_INPUT,
    MIKROTIK_WRITES_DISABLED,
    MIKROTIK_WRITE_CREDENTIALS_MISSING,
    DEVICE_BLOCK_WRITES_DISABLED,
    DEVICE_BLOCK_CONFLICT,
    MANAGED_BLOCK_RULE_DRIFT,
    AMBIGUOUS_OWNERSHIP,
    UNOWNED_BLOCK_RESOURCE,
    DEVICE_BLOCK_POSITION_UNSAFE,
    MIKROTIK_WRITE_PERMISSION_DENIED,
    MIKROTIK_WRITE_OUTCOME_UNKNOWN,
    MIKROTIK_POST_VERIFY_FAILED,
    MIKROTIK_OPERATION_FAILED,
    ROUTEROS_SNAPSHOT_UNAVAILABLE,
    RESOURCE_NOT_MANAGED,
    INTERNAL_ERROR
}
